name: Px.Utils CI

run-name: CI for PR ${{ github.event.pull_request.number }}

on: [ pull_request ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dotnet-version: [ '7.x', '8.x' ]
        configuration: [ Debug ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Install dotnet-coverage
        run: dotnet tool install -g dotnet-coverage

      - name: Install SonarCloud scanner
        run: dotnet tool install -g dotnet-sonarscanner

      - name: Begin SonarScanner
        run: dotnet sonarscanner begin /k:PxTools_Px.Utils
            /d:sonar.host.url=https://sonarcloud.io
            /d:sonar.token=${{ secrets.SONAR_TOKEN }}
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
            /o:pxtools

      - name: Build
        run: dotnet build --verbosity normal --no-restore --configuration ${{ matrix.configuration }}

      - name: Unit tests
        run: dotnet test --verbosity normal

      - name: Run coverage test
        run: dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

      - name: End SonarScanner
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}